<?php /** @var $this IntegerNet_GermanStoreConfig_Block_Frontend_Copyright */ ?>

<p>
    <?php echo Mage::helper('germanstoreconfig')->__('<a href="%s" target="_blank">Magento AT</a> is a project of the Magento community powered by <a href="%s" target="_blank">Netresearch App Factory</a>, <a href="%s" target="_blank">integer_net</a> &amp; <a href="%s" target="_blank">LimeSoda</a>',
        $this->getMagentoDEUrl(),
        $this->getAppFactoryUrl(),
        $this->getIntegerNetUrl(),
        $this->getLimeSodaUrl()) ?>
</p>